/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafootballboard.View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafootballboard.Controller.ArchivoController;
import javafootballboard.Controller.FiltroDeArchivos;
import javafootballboard.Model.Equipo;
import javafootballboard.Model.Jugador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mabel
 */
public class Equipos extends javax.swing.JFrame {

    public Subir subir = null;
    public Iniciar iniciar = null;
    private JFileChooser seleccionaArchivo;
    /**
     * Creates new form Equipos
     */
    public Equipos() {
        initComponents();
        cargarEquipos();
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        
    }
    
    public Equipos(Subir subir) {
        initComponents();
        cargarEquipos();
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        this.subir = subir;
    }
    
    public Equipos(Iniciar iniciar) {
        initComponents();
        cargarEquipos();
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        this.iniciar = iniciar;
    }
    
    public void cargarEquipos(){
        DefaultComboBoxModel modelE = new DefaultComboBoxModel();
        modelE.addElement("Seleccionar equipo...");
        System.out.println(ArchivoController.ac.equipos.entrySet().size());
        for( Map.Entry<String, Equipo> equipo : ArchivoController.ac.equipos.entrySet()){
            modelE.addElement(equipo.getKey());
        }
        equiposCargados.setModel(modelE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelGeneral = new javax.swing.JPanel();
        equiposCargados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        opcionManual = new javax.swing.JRadioButton();
        opcionAutomatico = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        seleccionado = new javax.swing.JLabel();
        botonSubir = new javax.swing.JButton();
        manualMessage = new javax.swing.JLabel();
        nombreEquipo = new javax.swing.JTextField();
        automaticMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equiposCargados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equiposCargadosMouseClicked(evt);
            }
        });
        equiposCargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposCargadosActionPerformed(evt);
            }
        });
        panelGeneral.add(equiposCargados, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 28, 239, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Jugadores");
        panelGeneral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 223, -1, -1));

        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Posición", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaJugadores.setCellSelectionEnabled(true);
        tablaJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJugadoresMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablaJugadoresMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tablaJugadores);

        panelGeneral.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 246, 432, 241));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelGeneral.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 505, -1, -1));

        jButton4.setText("Guardar equipo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelGeneral.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 505, -1, -1));

        opcionManual.setText("Manual");
        opcionManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionManualActionPerformed(evt);
            }
        });
        panelGeneral.add(opcionManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 97, -1, -1));

        opcionAutomatico.setText("Automático");
        opcionAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAutomaticoActionPerformed(evt);
            }
        });
        panelGeneral.add(opcionAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 123, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("¿Desea añadir otro equipo?");
        panelGeneral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 75, -1, -1));

        jLabel3.setText("Equipos cargados:");
        panelGeneral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 31, -1, -1));

        botonSeleccionar.setText("Seleccionar archivo");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });
        panelGeneral.add(botonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 174, -1, -1));

        seleccionado.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        seleccionado.setText("Archivo seleccionado");
        panelGeneral.add(seleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 178, -1, -1));

        botonSubir.setText("Subir");
        botonSubir.setEnabled(false);
        botonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirActionPerformed(evt);
            }
        });
        panelGeneral.add(botonSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 174, -1, -1));

        manualMessage.setText("Error/Success");
        panelGeneral.add(manualMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 101, 355, -1));

        nombreEquipo.setText("Nombre del equipo");
        nombreEquipo.setEnabled(false);
        nombreEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreEquipoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombreEquipoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nombreEquipoMouseReleased(evt);
            }
        });
        nombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEquipoActionPerformed(evt);
            }
        });
        nombreEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreEquipoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreEquipoKeyReleased(evt);
            }
        });
        panelGeneral.add(nombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 148, 192, -1));

        automaticMessage.setText("Error/Success");
        panelGeneral.add(automaticMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 127, 347, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/WhatsApp Image 2016-10-01 at 23.51.22.jpeg"))); // NOI18N
        panelGeneral.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        seleccionaArchivo = new JFileChooser ();
        seleccionaArchivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seleccionaArchivo.setFileFilter(new FiltroDeArchivos());
        seleccionaArchivo.setMultiSelectionEnabled(false);
        
        int returnVal = seleccionaArchivo.showOpenDialog(Equipos.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = seleccionaArchivo.getSelectedFile();
            seleccionado.setText(file.getName());
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getName() + ".");
        } else {
            System.out.println("Open command cancelled by user.");
        }
        botonSubir.setEnabled(true);
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    public void desactivarAutomatico(){
        opcionAutomatico.setSelected(false);
        opcionManual.setSelected(false);
        manualMessage.setVisible(false);
        automaticMessage.setVisible(true);
        equiposCargados.setEnabled(true);
        botonSeleccionar.setEnabled(false);
        nombreEquipo.setEnabled(false);
        botonSubir.setEnabled(false);
    }
    
    public void desactivarManual(){
        opcionManual.setSelected(false);
        opcionAutomatico.setSelected(false);
        botonSeleccionar.setEnabled(false);
        nombreEquipo.setEnabled(false);
        botonSubir.setEnabled(false);
        manualMessage.setVisible(true);
        automaticMessage.setVisible(false);
        equiposCargados.setEnabled(true);
    }
    
    private void opcionAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAutomaticoActionPerformed
        opcionManual.setSelected(false);
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        if(opcionAutomatico.isSelected()){
            equiposCargados.setEnabled(false);
            botonSeleccionar.setEnabled(true);
            nombreEquipo.setEnabled(true);
        }else{
            equiposCargados.setEnabled(true);
            botonSeleccionar.setEnabled(false);
            nombreEquipo.setEnabled(false);
            botonSubir.setEnabled(false);
        }
    }//GEN-LAST:event_opcionAutomaticoActionPerformed

    private void opcionManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionManualActionPerformed
        opcionAutomatico.setSelected(false);
        botonSeleccionar.setEnabled(false);
        nombreEquipo.setEnabled(false);
        botonSubir.setEnabled(false);
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        if(opcionManual.isSelected()){
            equiposCargados.setEnabled(false);
            EquipoRegistro equipoForm = new EquipoRegistro(this);
            equipoForm.setVisible(true);
            this.setEnabled(false);
        }else{
            equiposCargados.setEnabled(true);
        }
    }//GEN-LAST:event_opcionManualActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(subir != null){
            subir.setEnabled(true);
            subir.cargarComboBoxes();
            dispose();
            return;
        }
        if(iniciar != null){
            iniciar.setEnabled(true);
            iniciar.cargarComboBoxes();
            dispose();
            return;
        }
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void equiposCargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposCargadosActionPerformed
        if(equiposCargados.getSelectedIndex() == 0){
            DefaultTableModel modelT = new DefaultTableModel(0,0);
            tablaJugadores.setModel(modelT);
            return;
        }
        Equipo e = ArchivoController.ac.equipos.get(equiposCargados.getSelectedItem().toString());
        String[][] x = {};
        DefaultTableModel modelT = new DefaultTableModel(x, new String[]{"Nombre","Apellido","Posición","",""});
        tablaJugadores.setModel(modelT);
        int i = 0;
        for(Jugador jugador : e.getJugadores() ){
            modelT.insertRow(i, new Object[]{});
            modelT.setValueAt(jugador.getNombre(), i, 0);
            modelT.setValueAt(jugador.getApellido(), i, 1);
            modelT.setValueAt(jugador.getPosicion(), i, 2);
            JButton edit = new JButton("Editar");
            edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/edit.png")));
            modelT.setValueAt(new JButton("Editar").getIcon(), i, 3);
            modelT.setValueAt(new JButton("Eliminar"), i, 4);
            i++;
        }
    }//GEN-LAST:event_equiposCargadosActionPerformed

    private void botonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirActionPerformed
        automaticMessage.setVisible(false);
        if(nombreEquipo.getText().length() == 0 || nombreEquipo.getText().equals("Nombre del equipo")){
            automaticMessage.setText("Necesita nombrar su equipo");
            automaticMessage.setForeground(Color.red);
            automaticMessage.setVisible(true);
            return;
        }
        
        File f = seleccionaArchivo.getSelectedFile();
        if(!ArchivoController.ac.equipos.containsKey(nombreEquipo.getText())){
            ArchivoController.ac.equipos.put(nombreEquipo.getText(), new Equipo(nombreEquipo.getText()));
            ArchivoController.ac.cargarJugadores(f.getPath(), ArchivoController.ac.equipos.get(nombreEquipo.getText()));
        }else{
            automaticMessage.setText("Ya existe un equipo con este nombre");
            automaticMessage.setForeground(Color.red);
            automaticMessage.setVisible(true);
            return;
        }
        
        automaticMessage.setText("El archivo ha sido subido exitosamente");
        automaticMessage.setForeground(Color.green.darker());
        automaticMessage.setVisible(true);
        cargarEquipos();
        desactivarAutomatico();
        try {
            ArchivoController.ac.actEquipos();
        } catch (IOException ex) {
            Logger.getLogger(Equipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonSubirActionPerformed

    private void nombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEquipoActionPerformed

    }//GEN-LAST:event_nombreEquipoActionPerformed

    private void nombreEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEquipoMouseClicked
        if(nombreEquipo.getText().equals("Nombre del equipo")){
            nombreEquipo.setText("");
        }
    }//GEN-LAST:event_nombreEquipoMouseClicked

    private void nombreEquipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEquipoKeyPressed
        if(nombreEquipo.getText().equals("Nombre del equipo")){
            nombreEquipo.setText("");
        }
    }//GEN-LAST:event_nombreEquipoKeyPressed

    private void nombreEquipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEquipoMouseReleased
        
    }//GEN-LAST:event_nombreEquipoMouseReleased

    private void nombreEquipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEquipoKeyReleased
        if(nombreEquipo.getText().length() == 0){
            nombreEquipo.setText("Nombre del equipo");
        }
    }//GEN-LAST:event_nombreEquipoKeyReleased

    private void nombreEquipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEquipoMouseExited
        if(nombreEquipo.getText().length() == 0){
            nombreEquipo.setText("Nombre del equipo");
        }
    }//GEN-LAST:event_nombreEquipoMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(subir != null){
            subir.setEnabled(true);
            subir.cargarComboBoxes();
            subir.activarBotonA();
            dispose();
            return;
        }
        if(iniciar != null){
            iniciar.setEnabled(true);
            iniciar.cargarComboBoxes();
            dispose();
            return;
        }
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void equiposCargadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equiposCargadosMouseClicked
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
    }//GEN-LAST:event_equiposCargadosMouseClicked

    private void tablaJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJugadoresMouseClicked
        int r = tablaJugadores.getSelectedRow();
        int c = tablaJugadores.getSelectedColumn();
        if( tablaJugadores.getCellEditor() != null && 
                tablaJugadores.getCellEditor().getCellEditorValue().toString().equals("") ){
            tablaJugadores.getCellEditor().cancelCellEditing();
        }
    }//GEN-LAST:event_tablaJugadoresMouseClicked

    private void tablaJugadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJugadoresMouseExited
    }//GEN-LAST:event_tablaJugadoresMouseExited

    public void setManualText(String s, Boolean b){
        manualMessage.setVisible(false);
        manualMessage.setText(s);
        if(b){
            manualMessage.setForeground(Color.green.darker());
        }else{
            manualMessage.setForeground(Color.red);
        }
        manualMessage.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel automaticMessage;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JButton botonSubir;
    private javax.swing.JComboBox<String> equiposCargados;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manualMessage;
    private javax.swing.JTextField nombreEquipo;
    private javax.swing.JRadioButton opcionAutomatico;
    private javax.swing.JRadioButton opcionManual;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JLabel seleccionado;
    private javax.swing.JTable tablaJugadores;
    // End of variables declaration//GEN-END:variables
}
