/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafootballboard.View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import javafootballboard.Controller.FiltroDeArchivos;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author Mabel
 */
public class Equipos extends javax.swing.JFrame {

    /**
     * Creates new form Equipos
     */
    public Equipos() {
        initComponents();
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelGeneral = new javax.swing.JPanel();
        equiposCargados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        opcionManual = new javax.swing.JRadioButton();
        opcionAutomatico = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        seleccionado = new javax.swing.JLabel();
        botonSubir = new javax.swing.JButton();
        manualMessage = new javax.swing.JLabel();
        nombreEquipo = new javax.swing.JTextField();
        automaticMessage = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        equiposCargados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        equiposCargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposCargadosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Jugadores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Posición"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Cancelar");

        jButton4.setText("Guardar equipo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        opcionManual.setText("Manual");
        opcionManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionManualActionPerformed(evt);
            }
        });

        opcionAutomatico.setText("Automático");
        opcionAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAutomaticoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("¿Desea añadir otro equipo?");

        jLabel3.setText("Equipos cargados:");

        botonSeleccionar.setText("Seleccionar archivo");
        botonSeleccionar.setEnabled(false);
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        seleccionado.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        seleccionado.setText("Archivo seleccionado");

        botonSubir.setText("Subir");
        botonSubir.setEnabled(false);
        botonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirActionPerformed(evt);
            }
        });

        manualMessage.setText("Error/Success");

        nombreEquipo.setText("Nombre del equipo");
        nombreEquipo.setEnabled(false);
        nombreEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreEquipoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombreEquipoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nombreEquipoMouseReleased(evt);
            }
        });
        nombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEquipoActionPerformed(evt);
            }
        });
        nombreEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreEquipoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreEquipoKeyReleased(evt);
            }
        });

        automaticMessage.setText("Error/Success");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelGeneralLayout.createSequentialGroup()
                                    .addGap(144, 144, 144)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel2)
                                .addGroup(panelGeneralLayout.createSequentialGroup()
                                    .addComponent(opcionManual)
                                    .addGap(18, 18, 18)
                                    .addComponent(manualMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panelGeneralLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(equiposCargados, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelGeneralLayout.createSequentialGroup()
                                    .addComponent(opcionAutomatico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(automaticMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreEquipo)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addComponent(botonSeleccionar)
                                .addGap(10, 10, 10)
                                .addComponent(botonSubir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seleccionado)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equiposCargados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionManual)
                    .addComponent(manualMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionAutomatico)
                    .addComponent(automaticMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSeleccionar)
                    .addComponent(seleccionado)
                    .addComponent(botonSubir))
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        JFileChooser seleccionaArchivo = new JFileChooser ();
        seleccionaArchivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seleccionaArchivo.setFileFilter(new FiltroDeArchivos());
        seleccionaArchivo.setMultiSelectionEnabled(false);
        
        int returnVal = seleccionaArchivo.showOpenDialog(Equipos.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = seleccionaArchivo.getSelectedFile();
            seleccionado.setText(file.getName());
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getName() + ".");
        } else {
            System.out.println("Open command cancelled by user.");
        }
        botonSubir.setEnabled(true);
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void opcionAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAutomaticoActionPerformed
        opcionManual.setSelected(false);
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        if(opcionAutomatico.isSelected()){
            equiposCargados.setEnabled(false);
            botonSeleccionar.setEnabled(true);
            nombreEquipo.setEnabled(true);
        }else{
            equiposCargados.setEnabled(true);
            botonSeleccionar.setEnabled(false);
            nombreEquipo.setEnabled(false);
            botonSubir.setEnabled(false);
        }
    }//GEN-LAST:event_opcionAutomaticoActionPerformed

    private void opcionManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionManualActionPerformed
        opcionAutomatico.setSelected(false);
        botonSeleccionar.setEnabled(false);
        nombreEquipo.setEnabled(false);
        botonSubir.setEnabled(false);
        manualMessage.setVisible(false);
        automaticMessage.setVisible(false);
        if(opcionManual.isSelected()){
            equiposCargados.setEnabled(false);
            EquipoRegistro equipoForm = new EquipoRegistro(this);
            equipoForm.setVisible(true);
            this.setEnabled(false);
        }else{
            equiposCargados.setEnabled(true);
        }
    }//GEN-LAST:event_opcionManualActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void equiposCargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposCargadosActionPerformed

    }//GEN-LAST:event_equiposCargadosActionPerformed

    private void botonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirActionPerformed
        automaticMessage.setVisible(false);
        if(nombreEquipo.getText().length() == 0 || nombreEquipo.getText().equals("Nombre del equipo")){
            automaticMessage.setText("Necesita nombrar su equipo");
            automaticMessage.setForeground(Color.red);
            automaticMessage.setVisible(true);
        }
        
        automaticMessage.setText("El equipo ha sido subido exitosamente");
        automaticMessage.setForeground(Color.green.darker());
        automaticMessage.setVisible(true);
    }//GEN-LAST:event_botonSubirActionPerformed

    private void nombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEquipoActionPerformed

    }//GEN-LAST:event_nombreEquipoActionPerformed

    private void nombreEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEquipoMouseClicked
        if(nombreEquipo.getText().equals("Nombre del equipo")){
            nombreEquipo.setText("");
        }
    }//GEN-LAST:event_nombreEquipoMouseClicked

    private void nombreEquipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEquipoKeyPressed
        if(nombreEquipo.getText().equals("Nombre del equipo")){
            nombreEquipo.setText("");
        }
    }//GEN-LAST:event_nombreEquipoKeyPressed

    private void nombreEquipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEquipoMouseReleased
        
    }//GEN-LAST:event_nombreEquipoMouseReleased

    private void nombreEquipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEquipoKeyReleased
        if(nombreEquipo.getText().length() == 0){
            nombreEquipo.setText("Nombre del equipo");
        }
    }//GEN-LAST:event_nombreEquipoKeyReleased

    private void nombreEquipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEquipoMouseExited
        if(nombreEquipo.getText().length() == 0){
            nombreEquipo.setText("Nombre del equipo");
        }
    }//GEN-LAST:event_nombreEquipoMouseExited

    public void setManualText(String s, Boolean b){
        manualMessage.setVisible(false);
        manualMessage.setText(s);
        if(b){
            manualMessage.setForeground(Color.green.darker());
        }else{
            manualMessage.setForeground(Color.red);
        }
        manualMessage.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel automaticMessage;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JButton botonSubir;
    private javax.swing.JComboBox<String> equiposCargados;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel manualMessage;
    private javax.swing.JTextField nombreEquipo;
    private javax.swing.JRadioButton opcionAutomatico;
    private javax.swing.JRadioButton opcionManual;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JLabel seleccionado;
    // End of variables declaration//GEN-END:variables
}
