/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafootballboard.View;

import java.util.Map;
import javafootballboard.Controller.ArchivoController;
import static javafootballboard.Controller.ArchivoController.ac;
import javafootballboard.Controller.Archivos;
import javafootballboard.Model.Equipo;
import javafootballboard.Model.Juego;
import javafootballboard.Model.Jugador;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Naty
 */
public class Historico extends javax.swing.JFrame {

    /**
     * Creates new form Historico
     */
    public Historico() {
        initComponents();
        mostrarJuegos();
        
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaJuegos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Equipo A", "Punt. Equip. A", "Equipo B", "Punt. Equip. B", "Estadio", "Ciudad", "Fecha", "Inicio", "Fin", "Arbitro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaJuegos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaJuegos);
        tablaJuegos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /*===============Declaracion de Variables globales=========================*/
    String claveJuegos[]; //Almacena los codigos de los juegos activos
    
    
    
    
    
    
    
    /*Creación de metodo para mostrar todos los juegos Realizados*/
    private  void mostrarJuegos(){
        
        String[][] x = {};
        DefaultTableModel modeloTablaJuegos  = (DefaultTableModel) tablaJuegos.getModel();
       tablaJuegos.setModel(modeloTablaJuegos);
       int fila = 0;
     
       
        for( Map.Entry<String, Juego> juegoKey : ArchivoController.ac.juegos.entrySet()) {
          
              // Object[] orden = {datos[1],datos[2],datos[6],datos[7],datos[5],datos[3],datos[4],datos[8],datos[9]};
              Juego juego = ArchivoController.ac.juegos.get(juegoKey.getKey());
            
            modeloTablaJuegos.insertRow(fila, new Object[]{});
            modeloTablaJuegos.setValueAt(juego.getTitulo(), fila, 0);
            modeloTablaJuegos.setValueAt(juego.getEquipoA().getNombre(), fila, 1);
            modeloTablaJuegos.setValueAt(juego.getPuntosA(), fila, 2);
            modeloTablaJuegos.setValueAt(juego.getEquipoB().getNombre(), fila, 3);
            modeloTablaJuegos.setValueAt(juego.getPuntosB(), fila, 4);
            modeloTablaJuegos.setValueAt(juego.getEstadio(), fila, 5);
            modeloTablaJuegos.setValueAt(juego.getCiudad(), fila, 6);
            modeloTablaJuegos.setValueAt(juego.getFecha(), fila, 7);
            modeloTablaJuegos.setValueAt(juego.getHoraInicio(), fila, 8);
            modeloTablaJuegos.setValueAt(juego.getHoraFin(), fila, 9);
            modeloTablaJuegos.setValueAt(juego.getArbitro(), fila, 10);
            fila++;
            
             
           
       }
        
    } 
    private void obtenerFilaActiva(){
        ListSelectionModel modeloSeleccionTabla = tablaJuegos.getSelectionModel();
         modeloSeleccionTabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modeloSeleccionTabla.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                 if (tablaJuegos.getSelectedRow() > -1) {
            // print first column value from selected row
            System.out.println(tablaJuegos.getSelectedRow());
        }
                
            }
        
        });
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historico().setVisible(true);
            
            }
      
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tablaJuegos;
    // End of variables declaration//GEN-END:variables
}
