/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafootballboard.View;

import javafootballboard.Controller.AbrirVistas;


/**
 *
 * @author Mabel
 */
public class Menu extends javax.swing.JFrame {
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJuegosPasados = new javax.swing.JButton();
        botonEquipos = new javax.swing.JButton();
        botoIniciar = new javax.swing.JButton();
        botonSubirArchivos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBounds(new java.awt.Rectangle(0, 0, 840, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(840, 490));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonJuegosPasados.setFont(new java.awt.Font("Power Green Narrow", 1, 24)); // NOI18N
        botonJuegosPasados.setForeground(new java.awt.Color(204, 255, 255));
        botonJuegosPasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/history1.png"))); // NOI18N
        botonJuegosPasados.setText("Historico");
        botonJuegosPasados.setBorderPainted(false);
        botonJuegosPasados.setContentAreaFilled(false);
        botonJuegosPasados.setFocusPainted(false);
        botonJuegosPasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonJuegosPasados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/history2.png"))); // NOI18N
        botonJuegosPasados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/history2.png"))); // NOI18N
        botonJuegosPasados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/history2.png"))); // NOI18N
        botonJuegosPasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonJuegosPasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJuegosPasadosActionPerformed(evt);
            }
        });
        getContentPane().add(botonJuegosPasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 130, 110));

        botonEquipos.setFont(new java.awt.Font("Power Green Narrow", 1, 24)); // NOI18N
        botonEquipos.setForeground(new java.awt.Color(204, 255, 255));
        botonEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/teams1.png"))); // NOI18N
        botonEquipos.setText("Equipos");
        botonEquipos.setBorder(null);
        botonEquipos.setBorderPainted(false);
        botonEquipos.setContentAreaFilled(false);
        botonEquipos.setFocusPainted(false);
        botonEquipos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEquipos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/teams2.png"))); // NOI18N
        botonEquipos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/teams2.png"))); // NOI18N
        botonEquipos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(botonEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 110, 110));

        botoIniciar.setFont(new java.awt.Font("Power Green Narrow", 1, 24)); // NOI18N
        botoIniciar.setForeground(new java.awt.Color(51, 51, 51));
        botoIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/play1.png"))); // NOI18N
        botoIniciar.setText("Iniciar");
        botoIniciar.setBorderPainted(false);
        botoIniciar.setContentAreaFilled(false);
        botoIniciar.setFocusPainted(false);
        botoIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botoIniciar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/play2.png"))); // NOI18N
        botoIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/play2.png"))); // NOI18N
        botoIniciar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/play2.png"))); // NOI18N
        botoIniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botoIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 110));

        botonSubirArchivos.setFont(new java.awt.Font("Power Green Narrow", 1, 24)); // NOI18N
        botonSubirArchivos.setForeground(new java.awt.Color(204, 255, 255));
        botonSubirArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/upload2.png"))); // NOI18N
        botonSubirArchivos.setText("Cargar");
        botonSubirArchivos.setBorderPainted(false);
        botonSubirArchivos.setContentAreaFilled(false);
        botonSubirArchivos.setFocusPainted(false);
        botonSubirArchivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSubirArchivos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/upload3.png"))); // NOI18N
        botonSubirArchivos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/upload3.png"))); // NOI18N
        botonSubirArchivos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSubirArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(botonSubirArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 120, 110));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/logot.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javafootballboard/Assets/fondo.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(750, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(750, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -20, 1120, 580));
        jLabel2.getAccessibleContext().setAccessibleParent(jLabel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEquiposActionPerformed
        AbrirVistas.equipos(this);
    }//GEN-LAST:event_botonEquiposActionPerformed

    private void botoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoIniciarActionPerformed
        AbrirVistas.iniciar(this);
    }//GEN-LAST:event_botoIniciarActionPerformed

    private void botonSubirArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirArchivosActionPerformed
        AbrirVistas.subir(this);
    }//GEN-LAST:event_botonSubirArchivosActionPerformed

    private void botonJuegosPasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJuegosPasadosActionPerformed
        AbrirVistas.historico(this);
    }//GEN-LAST:event_botonJuegosPasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoIniciar;
    private javax.swing.JButton botonEquipos;
    private javax.swing.JButton botonJuegosPasados;
    private javax.swing.JButton botonSubirArchivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
